[nora]
packages = ["nora-registry"]
engine = "Llvm"
fail-under = 38
out = ["json", "html"]
output-dir = "coverage"
timeout = "300"
exclude-files = ["src/ui/*", "src/main.rs", "src/openapi.rs"]
workspace = false
